version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "mstar_supply_db"
      POSTGRES_USER: "mstar_supply"
      POSTGRES_PASSWORD: ""
      ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "5432:5432"
    volumes:
      - dash_pgsql_volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@mstar.dev"
      PGADMIN_DEFAULT_PASSWORD: ""
    ports:
      - "16543:80"
    depends_on:
      - db

volumes:
  dash_pgsql_volume: