Vagrant.configure("2") do |config|
    config.vm.network "public_network"
    config.vm.define "mstar-srv" do |server|
        server.vm.box = "ubuntu/xenial64"
		server.vm.box_version = "20211001.0.0"
        server.vm.hostname = "mstar-srv"
        server.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "1"
            vb.name = "mstar-srv"
        end
    end
end